### ISSUE TITLE
Error 403 on POST https://apptoogoodtogo.com/api/auth/v3/token/refresh

### ISSUE THREAD

**Issue by basti1499** [marklagendijk/node-toogoodtogo-watcher#212]
I am experiencing the following 403 error:

```
Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
{
    "refresh_token": "[removed]"
}

HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

No known fix yet.

Will update this post if I find a solution.

**Comment by marklagendijk** [comment]
I also have this. Up till now it usually goes away after a bit.

**Comment by marklagendijk** [comment]
I did just release a new version, `3.9.2` in which the API version has been stepped.

**Comment by basti1499** [comment]
> I did just release a new version, `3.9.2` in which the API version has been stepped.

Already tried it with `3.9.2`, but the error message stays the same.
If I'm not wrong, the change in `3.9.2` was the item API from v7 to v8, the error here refers to the auth API not working. Changing it to v4 didn't help either as it results in HTTP 404 error.

**Comment by winus** [comment]
> > I did just release a new version, `3.9.2` in which the API version has been stepped.
> 
> Already tried it with `3.9.2`, but the error message stays the same. If I'm not wrong, the change in `3.9.2` was the item API from v7 to v8, the error here refers to the auth API not working. Changing it to v4 didn't help either as it results in HTTP 404 error.

Running with latest version, still same issue here.

**Comment by c0lumb0** [comment]
> I am experiencing the following 403 error:
> 
> ```
> Error during request:
> POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
> {
>     "refresh_token": "[removed]"
> }
> 
> HTTPError: Response code 403 (Forbidden)
>     at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> ```
> 
> No known fix yet.
> 
> Will update this post if I find a solution.

This should be the datadome cookie issue, as far as I can see, since it is the same error message also in here

https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/201

Since adding this fix, I don't get this issue anymore.

**Comment by winus** [comment]
> > I am experiencing the following 403 error:
> > ```
> > Error during request:
> > POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
> > {
> >     "refresh_token": "[removed]"
> > }
> > 
> > HTTPError: Response code 403 (Forbidden)
> >     at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
> >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > No known fix yet.
> > Will update this post if I find a solution.
> 
> This should be the datadome cookie issue, as far as I can see, since it is the same error message also in here
> 
> #201
> 
> Since adding this fix, I don't get this error anymore.

Check, me too.

**Comment by dferrandizmont** [comment]
> > > I am experiencing the following 403 error:
> > > ```
> > > Error during request:
> > > POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
> > > {
> > >     "refresh_token": "[removed]"
> > > }
> > > 
> > > HTTPError: Response code 403 (Forbidden)
> > >     at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
> > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > No known fix yet.
> > > Will update this post if I find a solution.
> > 
> > 
> > This should be the datadome cookie issue, as far as I can see, since it is the same error message also in here
> > #201
> > Since adding this fix, I don't get this error anymore.
> 
> Check, me too.

Have you been able to fix it? `https://apptoogoodtogo.com/api/auth/v3/token/refresh` always gives me `405` no matter if I try it over VPN.

**Comment by basti1499** [comment]
> > > > I am experiencing the following 403 error:
> > > > ```
> > > > Error during request:
> > > > POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
> > > > {
> > > >     "refresh_token": "[removed]"
> > > > }
> > > > 
> > > > HTTPError: Response code 403 (Forbidden)
> > > >     at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
> > > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > No known fix yet.
> > > > Will update this post if I find a solution.
> > > 
> > > 
> > > This should be the datadome cookie issue, as far as I can see, since it is the same error message also in here
> > > #201
> > > Since adding this fix, I don't get this error anymore.
> > 
> > 
> > Check, me too.
> 
> Have you been able to fix it? `https://apptoogoodtogo.com/api/auth/v3/token/refresh` always gives me `405` no matter if I try it over VPN.

The `405` response code indicates that the http method you used is not allowed by this endpoint. If you paste the given URL into your browser and open it, it will send a `GET` request which get's denied, because the endpoint only supports `POST` requests. This shouldn't be an issue though, the datadome cookie still gets set.

**Comment by dferrandizmont** [comment]
> > > > > I am experiencing the following 403 error:
> > > > > ```
> > > > > Error during request:
> > > > > POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
> > > > > {
> > > > >     "refresh_token": "[removed]"
> > > > > }
> > > > > 
> > > > > HTTPError: Response code 403 (Forbidden)
> > > > >     at Request.<anonymous> (/usr/lib/node_modules/toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:118:42)
> > > > >     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > No known fix yet.
> > > > > Will update this post if I find a solution.
> > > > 
> > > > 
> > > > This should be the datadome cookie issue, as far as I can see, since it is the same error message also in here
> > > > #201
> > > > Since adding this fix, I don't get this error anymore.
> > > 
> > > 
> > > Check, me too.
> > 
> > 
> > Have you been able to fix it? `https://apptoogoodtogo.com/api/auth/v3/token/refresh` always gives me `405` no matter if I try it over VPN.
> 
> The `405` response code indicates that the http method you used is not allowed by this endpoint. If you paste the given URL into your browser and open it, it will send a `GET` request which get's denied, because the endpoint only supports `POST` requests. This shouldn't be an issue though, the datadome cookie still gets set.
> 
> Edit: in Chromium based browsers you can find it in the dev tools (F12) under application > cookies

You're totally right! Got the cookie. Let's see if tomorrow is working again :). Thanks @basti1499

**Comment by marklagendijk** [comment]
I released a new version `3.10.0` that hopefully fixes this issue.
Based on the above it seems that the following happens:
* The request gets denied because of a missing cookie, but this cookie is set via the error response.
* By manually adding the cookie subsequent requests actually work.

Now we already have support for cookies via a `cookieJar`, so the only thing missing should be retrying a request after a failure, because the next request should have the cookie.

I did this by configuring retries, and it seems to work.
Please let me know whether this works for you.

**Comment by basti1499** [comment]
> I released a new version `3.10.0` that hopefully fixes this issue. Based on the above it seems that the following happens:
> 
> * The request gets denied because of a missing cookie, but this cookie is set via the error response.
> * By manually adding the cookie subsequent requests actually work.
> 
> Now we already have support for cookies via a `cookieJar`, so the only thing missing should be retrying a request after a failure, because the next request should have the cookie.
> 
> I did this by configuring retries, and it seems to work. Please let me know whether this works for you.

I updated to `3.10.0` and I don't get any error message anymore, but I also don't get any other message.
Will try again this evening.

I started with a fresh installation, anything else to do than regular installation (and adding the cookie to the header)?

**Comment by WhoTheHeck** [comment]
I updated too. Still got the error message. I now applied the steps from https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/201#issuecomment-1399465383, which successfully solved the issue.

**Comment by Hondai96** [comment]
Also facing the problem that everything seems to work, but no notifications. I reinstalled everything to be sure, login in works and config is fine. But when I try to do the fix in [#201 ](https://github.com/marklagendijk/node-toogoodtogo-watcher/issues/201#issuecomment-1399465383), it fails for me because I cannot do any capture. Do you have a suggestion here?

**Comment by marklagendijk** [comment]
The idea is that with the latest version it should _automatically_ get the required cookie, because it sets it when it fails, and then retries the request. This would not work if you manually configure a cookie header, because that will override the automatic cookie.
That being said, as soon as you run into things like a CAPTCHA, this will still not work.

> Is it possible to enable some more verbose output for debugging?
I should look into that at some point. Maybe there is something that works by default (via certain environment variables, for example), but maybe something needs to be setup in code.

**Comment by jpallares** [comment]
I've been using the watcher from a docker container running in a home server and receiving notifications via Telegram bot. 

9th of February it stopped working. I tried setting up manually the datadome cookie as suggested but only worked for some hours.

I deleted everything (docker image, config back to default, telegram bot) and made sure it downloaded the latest docker image, still not working, when trying to login via telegram bot I get the following error and never receive an email:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1519657/221373025-061fd1b1-139e-4d70-a8a0-4c8d23b33090.png">

`Something went wrong
"HTTPError: Response code 403 (Forbidden)\n    at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)"`

anybody with a similar setup with the same issue?

**Comment by dmitrybabich** [comment]
> `Something went wrong "HTTPError: Response code 403 (Forbidden)\n at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)"`
> 
> anybody with a similar setup with the same issue?

yes, I have exactly the same issue

**Comment by Swing764** [comment]
> > I released a new version `3.10.0` that hopefully fixes this issue. Based on the above it seems that the following happens:
> > 
> > * The request gets denied because of a missing cookie, but this cookie is set via the error response.
> > * By manually adding the cookie subsequent requests actually work.
> > 
> > Now we already have support for cookies via a `cookieJar`, so the only thing missing should be retrying a request after a failure, because the next request should have the cookie.
> > I did this by configuring retries, and it seems to work. Please let me know whether this works for you.
> 
> I updated to `3.10.0` and I don't get any error message anymore, but I also don't get any other message. Will try again this evening.
> 
> I started with a fresh installation, anything else to do than regular installation (and adding the cookie to the header)? It feels like the bot isn't sending any API calls, atleast I couldn't find it in the network traffic. Is it possible to enable some more verbose output for debugging?

Same procedure and same behaviour here.
Using last nodejs on windows, fresh install, enabled telegram bot and copied the botToken in config. Logged in via the bot is working, but no error messages and no notifications at all.

Anyone got it to work with version 3.10.0?

**Comment by marklagendijk** [comment]
I fixed an issue and updated all dependencies.
Please try `3.10.2`.

**Comment by Swing764** [comment]
> I fixed an issue and updated all dependencies. Please try `3.10.2`.

Everything seems working fine now. Thanks!

**Comment by marklagendijk** [comment]
I expect that all issues with this are now fixed, except for the case where datadome asks to solve a CAPTCHA.
If this is not the case, let me know.

**Comment by jpallares** [comment]
> I've been using the watcher from a docker container running in a home server and receiving notifications via Telegram bot.
> 
> 9th of February it stopped working. I tried setting up manually the datadome cookie as suggested but only worked for some hours.
> 
> I deleted everything (docker image, config back to default, telegram bot) and made sure it downloaded the latest docker image, still not working, when trying to login via telegram bot I get the following error and never receive an email:
> 
> <img alt="image" width="1034" src="https://user-images.githubusercontent.com/1519657/221373025-061fd1b1-139e-4d70-a8a0-4c8d23b33090.png">
> 
> `Something went wrong "HTTPError: Response code 403 (Forbidden)\n at Request.<anonymous> (/home/node/app/node_modules/got/dist/source/as-promise/index.js:117:42)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)"`
> 
> anybody with a similar setup with the same issue?

Sorry but in my case is not fixes and I'm still getting the error even with the new version 3.10.2 @marklagendijk

**Comment by dmitrybabich** [comment]
Also tried it today: pulled the fresh docker image, restarted everything, but still the same error.

**Comment by Gibey000** [comment]
I also have the error message : HTTPError: Response code 403 (Forbidden)    at Request.<anonymous>

**Comment by dmitrybabich** [comment]
I have this error again as well, and can't seem to solve it by resetting configs/changing emails

```
Error during request:
POST https://apptoogoodtogo.com/api/auth/v3/token/refresh
undefined

HTTPError: Response code 403 ()
```

Is there any known workaround at the moment?

**Comment by TobiasCurth** [comment]
I tried it again by starting the login request via docker:
`
docker run \
 -i \
 --name toogoodtogo-watcher-test \
 --rm \
 -v /data/toogoodtogo:/home/node/.config/toogoodtogo-watcher-nodejs \
 marklagendijk/toogoodtogo-watcher login --email *****@googlemail.com
Something went wrong: HTTPError: Response code 403 (Forbidden)
    at Request.<anonymous> (file:///home/node/app/node_modules/got/dist/source/as-promise/index.js:86:42)
    at Object.onceWrapper (node:events:628:26)
    at Request.emit (node:events:525:35)
    at Request._onResponseBase (file:///home/node/app/node_modules/got/dist/source/core/index.js:726:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Request._onResponse (file:///home/node/app/node_modules/got/dist/source/core/index.js:765:13) {
  input: undefined,
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1677956507193,
    socket: 1677956507193,
    lookup: 1677956507215,
    connect: 1677956507240,
    secureConnect: 1677956507271,
    upload: 1677956507271,
    response: 1677956507328,
    end: 1677956507329,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 22,
      tcp: 25,
      tls: 31,
      request: 0,
      firstByte: 57,
      download: 1,
      total: 136
    }
  },
  options: {
    request: undefined,
    agent: { http: undefined, https: undefined, http2: undefined },
    h2session: undefined,
    decompress: true,
    timeout: {
      connect: undefined,
      lookup: undefined,
      read: undefined,
      request: undefined,
      response: undefined,
      secureConnect: undefined,
      send: undefined,
      socket: undefined
    },
    prefixUrl: '',
    body: '{"device_type":"IOS","email":"****@googlemail.com"}',
    form: undefined,
    json: undefined,
    cookieJar: CookieJar {
      rejectPublicSuffixes: true,
      enableLooseMode: false,
      allowSpecialUseDomain: true,
      store: { idx: {
        'apptoogoodtogo.com': {
          '/': {
            datadome: Cookie="datadome=56oQ2S~ilHGMOJ38WenYgvR-0KcB3Od58oNM--W7eGARzghjA~JqD7Sc3h_illb1ScPhRHoZNHAtwCUDKzYV-[...]; Max-Age=31536000; Domain=apptoogoodtogo.com; Path=/; Secure; SameSite=Lax; hostOnly=false; aAge=5ms; cAge=3446ms"
          }
        }
      } },
      prefixSecurity: 'silent',
      _cloneSync: [Function (anonymous)],
      _importCookiesSync: [Function (anonymous)],
      getCookiesSync: [Function (anonymous)],
      getCookieStringSync: [Function (anonymous)],
      getSetCookieStringsSync: [Function (anonymous)],
      removeAllCookiesSync: [Function (anonymous)],
      setCookieSync: [Function (anonymous)],
      serializeSync: [Function (anonymous)]
    },
    ignoreInvalidCookies: false,
    searchParams: undefined,
    dnsLookup: undefined,
    dnsCache: undefined,
    context: {},
    hooks: {
      init: [],
      beforeRequest: [],
      beforeError: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: []
    },
    followRedirect: true,
    maxRedirects: 10,
    cache: undefined,
    throwHttpErrors: true,
    username: '',
    password: '',
    http2: false,
    allowGetBody: false,
    headers: {
      'user-agent': 'TooGoodToGo/21.9.0 (813) (iPhone/iPhone 7 (GSM); iOS 15.1; Scale/2.00)',
      'content-type': 'application/json',
      accept: '',
      'accept-language': 'en-US',
      'accept-encoding': 'gzip',
      'content-length': '55',
      cookie: 'datadome=3SQdMtZ7pOVB1Z-cYCfoxBCGsxQkAMtDGgIk-kA5MdBWqAuK_k_[...]'
    },
    methodRewriting: false,
    dnsLookupIpVersion: undefined,
    parseJson: [Function: parse],
    stringifyJson: [Function: stringify],
    retry: {
      limit: 2,
      methods: [
        'GET',    'POST',
        'PUT',    'HEAD',
        'DELETE', 'OPTIONS',
        'TRACE'
      ],
      statusCodes: [
        401, 403, 408, 413,
        429, 500, 502, 503,
        504, 521, 522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },
    localAddress: undefined,
    method: 'POST',
    createConnection: undefined,
    cacheOptions: {
      shared: undefined,
      cacheHeuristic: undefined,
      immutableMinTimeToLive: undefined,
      ignoreCargoCult: undefined
    },
    https: {
      alpnProtocols: undefined,
      rejectUnauthorized: undefined,
      checkServerIdentity: undefined,
      certificateAuthority: undefined,
      key: undefined,
      certificate: undefined,
      passphrase: undefined,
      pfx: undefined,
      ciphers: undefined,
      honorCipherOrder: undefined,
      minVersion: undefined,
      maxVersion: undefined,
      signatureAlgorithms: undefined,
      tlsSessionLifetime: undefined,
      dhparam: undefined,
      ecdhCurve: undefined,
      certificateRevocationLists: undefined
    },
    encoding: undefined,
    resolveBodyOnly: true,
    isStream: false,
    responseType: 'json',
    url: URL {
      href: 'https://apptoogoodtogo.com/api/auth/v3/authByEmail',
      origin: 'https://apptoogoodtogo.com',
      protocol: 'https:',
      username: '',
      password: '',
      host: 'apptoogoodtogo.com',
      hostname: 'apptoogoodtogo.com',
      port: '',
      pathname: '/api/auth/v3/authByEmail',
      search: '',
      searchParams: URLSearchParams {},
      hash: ''
    },
    pagination: {
      transform: [Function: transform],
      paginate: [Function: paginate],
      filter: [Function: filter],
      shouldContinue: [Function: shouldContinue],
      countLimit: Infinity,
      backoff: 0,
      requestLimit: 10000,
      stackAllItems: false
    },
    setHost: true,
    maxHeaderSize: undefined,
    signal: undefined,
    enableUnixSockets: true
  }
}
`

config.json:
`
	"api": {
		"credentials": {
			"email": "***@googlemail.com"
		},
		"session": {},
		"deviceType": "IOS",
		"headers": {},
		"pollingIntervalInMs": 30000,
		"authenticationIntervalInMS": 3600000
	},
[...]
`

Do you have some more ideas how I can debug it?

**Comment by jpallares** [comment]
Just tried without success

Can I help somehow? Do you need any extra logs/info?

<img width="706" alt="image" src="https://user-images.githubusercontent.com/1519657/225320452-a2bd87c7-83cc-4003-80b0-e782d40d062c.png">

**Comment by marklagendijk** [comment]
Few points:
- Be sure to remove the custom Cookie header, if you configured any.
- Do not run the application in the cloud. Cloud are blocked.
- It is always possible that your personal IP gets blocked (usually temporarily).
- Do not run multiple instances of the application, or make the polling interval more frequent (only possible by actually adjusting the code), because you will get blocked.

**Comment by basti1499** [comment]
> * Do not run multiple instances of the application, or make the polling interval more frequent (only possible by actually adjusting the code), because you will get blocked.

Can't this be adjusted in the config file?
"pollingIntervalInMs": 30000,
"authenticationIntervalInMS": 3600000

**Comment by marklagendijk** [comment]
Yes, it can.
But I thought that the default polling interval was the same as the [enforced minimum](https://github.com/marklagendijk/node-toogoodtogo-watcher/blob/3cfab6ddf282a9fe3f86c7c8a746fd83ea702a17/lib/poller.js#L7), but the enforced minimum is 15 seconds.

Hmm, maybe I should increase one or both.

**Comment by dmitrybabich** [comment]
> 
>     * Do not run the application in the cloud. Cloud are blocked.
> 
>     * It is always possible that your personal IP gets blocked (usually temporarily).
> 

That was the cause of the issue for me! Once I run it on my local Raspberry Pi, I don't get this error anymore.  Maybe it's worth adding to README.

**Comment by AndreaVida** [comment]
> Few points:
> 
> * Be sure to remove the custom Cookie header, if you configured any.
> * Do not run the application in the cloud. Cloud are blocked.
> * It is always possible that your personal IP gets blocked (usually temporarily).
> * Do not run multiple instances of the application, or make the polling interval more frequent (only possible by actually adjusting the code), because you will get blocked.

Updated to version 4.0.3 and removed Cookie header from config but still getting 403 error due to datadome cookie. Does this mean my personal IP address got blocked by TGTG?

**Comment by nurp** [comment]
back to the same issue but "undefined" 404 error:
POST https://apptoogoodtogo.com/api/auth/v4/token/refresh
undefined

version 4.0.6
