### ISSUE TITLE
No activity in watcher

### ISSUE THREAD

**Issue by nurp** [marklagendijk/node-toogoodtogo-watcher#261]
It has stopped about 2 months ago. Is it possible that I am banned? I installed it on completely new computer etc but no luck.
Now I am debugging. Please help me find the issue.

I run the latest version.
 
```
$ DEBUG=* node index.js watch
  telegraf:main Created a `Telegraf` instance +0ms
  telegraf:main Connecting to Telegram +0ms
  telegraf:client HTTP call getMe {} +0ms
  telegraf:main Launching @****************[hidden] +82ms
  telegraf:client HTTP call deleteWebhook { drop_pending_updates: undefined } +82ms
  telegraf:main Bot started with long polling +18ms
  telegraf:polling Starting long polling +0ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 0, allowed_updates: [] } +18ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 0, allowed_updates: [] } +50s
...
chat_id: ****************[hidden],
  message_thread_id: undefined,
  text: '🔧 Of course !\n' +
    'Enabled : ✅\n' +
    'Activate alert for unchanged stock : ✅\n' +
    'Activate alert for decreasing stock : ✅\n' +
    'Activate alert for sold out : ✅\n' +
    'Activate alert for increasing stock : ✅\n' +
    'Activate alert for new market available : ✅\n' +
    '  '
} +4s
  telegraf:main Finished processing update 863551085 +3ms
  telegraf:client HTTP call getUpdates { timeout: 50, offset: 863551086, allowed_updates: [] } +1ms


```
On telegram I enabled all the messages and see these outputs.
What else can I debug?

**Comment by dekoningh** [comment]
> I clicked on /login in telegram settings (before I logged in from command line), now I see this error which I didn't see before either:
> 
> ```
> Error during request:
> POST https://apptoogoodtogo.com/api/item/v8/
> undefined
> 
> HTTPError: Response code 403 (Forbidden)
>     at Request.<anonymous> (file:///Users/nurpinar/projects/node-toogoodtogo-watcher/node_modules/got/dist/source/as-promise/index.js:86:42)
>     at Object.onceWrapper (node:events:622:26)
>     at Request.emit (node:events:519:35)
>     at Request._onResponseBase (file:///Users/nurpinar/projects/node-toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:726:22)
>     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
>     at async Request._onResponse (file:///Users/nurpinar/projects/node-toogoodtogo-watcher/node_modules/got/dist/source/core/index.js:765:13)
> ```
> 
> I've tried to change v8 to v9, same.

Can confirm this. Updated user-agent header to newest (25.4.1) version as well, without succes.

**Comment by Cook-EZ** [comment]
based on 
# https://github.com/michelheusschen/tgtg/commit/aa5d75ced2f973c426f730b657cf514d46094370

it sounds like the session needs a UUID. I generated a UUID4 based on google search

in the tgoogoodtogo-api.js file > add a new row/item into >"headers: _.defaults(config.get("api.headers"), {"
this `"x-correlation-id": "<your UUID4 code here>`

**Comment by Slothoncrack** [comment]
Can confirm that @Cook-EZ 's method solved the 403 error for me, restoring the monitoring.

**Comment by c0lumb0** [comment]
Can someone please create a PR?
For me this is not solving the issue rn, just creating a 401 error instead of a 403.
Maybe reinstalling the application from scratch and applying the solution would be worth a try as well

**Comment by Slothoncrack** [comment]
> Can someone please create a PR? For me this is not solving the issue rn, just creating a 401 error instead of a 403. Maybe reinstalling the application from scratch and applying the solution would be worth a try as well

Did you relogin? 401 usually is solved by that

**Comment by nurp** [comment]
I still get 403. 
I have datadome, last version getter, x-correlation-id, logged in again. nothing changes.

**Comment by github-marsup** [comment]
> I still get 403. I have datadome, last version getter, x-correlation-id, logged in again. nothing changes.

Try to remove datadom cookie. That works for me

**Comment by basti1499** [comment]
I'll create a PR, but I am not sure whether this is the optimal approach. The way I implemented it a new correlation ID gets created for every request. The idea was to avoid bot-detection by having too many requests with the same correlation ID.

**Comment by c0lumb0** [comment]
> > Can someone please create a PR? For me this is not solving the issue rn, just creating a 401 error instead of a 403. Maybe reinstalling the application from scratch and applying the solution would be worth a try as well
> 
> Did you relogin? 401 usually is solved by that

OK, got it working now.

I know what my issue was, what maybe is also the issue of someone else here, if the application is still not working after the mentioned UUID4 change in the API header. You cannot use a random online generated UUID, you have to use the UUID which is created by the login process, which is shown in the URL after you have clicked the email you receive for authorization.

Just relogging in does not work.

**Comment by basti1499** [comment]
> [...] You cannot use a random online generated UUID, you have to use the UUID which is created by the login process, which is shown in the URL after you have clicked the email you receive for authorization. [...]

This doesn't really make sense to me. Correlation IDs are usually used to track requests across multiple services or servers. They are not used for any authentication purposes because they are neither encrypted nor signed and can therefore easily be manipulated.

Interestingly my attempt to fix it is working for some time, but stops working eventually. Anyways, let's see if somebody can come up with a solution, I'll let you know if I find anything.

**Comment by ralfbosz** [comment]
I used your change, upped the version and charges the Phone. Seems to work. See if it lasts.

**Comment by basti1499** [comment]
> I used your change, upped the version and changed the Phone value. Seems to work. See if it lasts.

Which approach did you take? (correlation ID created once or correlation ID updated from time to time)
Did it work consistently?

For me it looks like using the same correlation ID all the time works better than recreating them for every request, even though I don't understand why. When the correlation ID gets recreated every time, it works for a long time, and then suddenly stops - still trying to find out why.

**Comment by ralfbosz** [comment]
I used the now closed #262 

And changed in this file the Useragent part (line 12) to use the new version of tgtg 25.4.11 and the Samsung part to another phone.

Still going strong...

**Comment by basti1499** [comment]
> I used the now closed [#262](https://github.com/marklagendijk/node-toogoodtogo-watcher/pull/262)

That is very interesting - I closed it because it didn't work consistently for me. I am running some tests with separate approaches and will re-open the PR in case it works.

**Comment by ralfbosz** [comment]
Just using your file worked for less then day. The version and Samsung change was just seeing if that works.

There is a change to read the version and use it, that would be welcome. Maybe the Samsung part should be a random pick from an array.

**Comment by c0lumb0** [comment]
Since I added the UUID that you get via log-in in the URL, I did not have any issues and the application is working just fine.

**Comment by marklagendijk** [comment]
I released `4.0.8`. Let me know if it fixes everything.

**Comment by nurp** [comment]
Omg, it worked for the first tim since ages! 
It even removed a "stranger listener" whyever and whoever does that!

**Comment by casudo** [comment]
v4.0.8 fixed the problem for me.

**Comment by maarten551** [comment]
Even when I try to login I get a 403 now.

I updated to the newest version, and removed my old config file, but still getting a 403 at login.
